/**
* This file was generated by st-open-api
*/
import {PetService} from '../service/pet-service';
import {StoreService} from '../service/store-service';
import {UserService} from '../service/user-service';

export const PET_SERVICE = new PetService();
export const STORE_SERVICE = new StoreService();
export const USER_SERVICE = new UserService();

if (process.env.NODE_ENV !== 'production') {
    // eslint-disable-next-line no-console
    console.groupCollapsed('Constant Services registered');
    // eslint-disable-next-line no-console
    console.info(PET_SERVICE);
    // eslint-disable-next-line no-console
    console.info(STORE_SERVICE);
    // eslint-disable-next-line no-console
    console.info(USER_SERVICE);
    // eslint-disable-next-line no-console
    console.groupEnd();
}
