/**
 * This file was generated by st-open-api
 */
import {IStatusFindPetsByStatus} from './enumeration/i-status-find-pets-by-status';

export interface IFindPetsByStatusQueryParameter {

    status?: IStatusFindPetsByStatus;

}
