/**
 * This file was generated by st-open-api
 */
import {IStatusOrder} from './enumeration/i-status-order';

export interface IOrder {

    complete?: boolean;

    id?: number;

    petId?: number;

    quantity?: number;

    shipDate?: string;

    status?: IStatusOrder;

}
