/**
 * This file was generated by st-open-api
 */
import {ICategory} from './i-category';
import {IStatusPet} from './enumeration/i-status-pet';
import {ITag} from './i-tag';

export interface IPet {

    category?: ICategory;

    id?: number;

    name: string;

    photoUrls: Array<string>;

    status?: IStatusPet;

    tags?: Array<ITag>;

}
