/**
 * This file was generated by st-open-api
 */

export interface IUser {

    email?: string;

    firstName?: string;

    id?: number;

    lastName?: string;

    password?: string;

    phone?: string;

    username?: string;

    userStatus?: number;

}
